// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHephvCyyD5Gy1Ga0hbfQUZSIDYgCziA',
    appId: '1:994981518011:web:289b3d36dee3f712d1279e',
    messagingSenderId: '994981518011',
    projectId: 'carstats-8585a',
    authDomain: 'carstats-8585a.firebaseapp.com',
    databaseURL: 'https://carstats-8585a-default-rtdb.firebaseio.com',
    storageBucket: 'carstats-8585a.appspot.com',
    measurementId: 'G-MQVVSYQSXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhN3HhuE2HOdfpqdTz3jO3uJzNCLJHQos',
    appId: '1:994981518011:android:6caec4eee3dccfd0d1279e',
    messagingSenderId: '994981518011',
    projectId: 'carstats-8585a',
    databaseURL: 'https://carstats-8585a-default-rtdb.firebaseio.com',
    storageBucket: 'carstats-8585a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC12zLSq8YyJ2ivXLAU9neB7-7IUDJNByE',
    appId: '1:994981518011:ios:1b7581335872623fd1279e',
    messagingSenderId: '994981518011',
    projectId: 'carstats-8585a',
    databaseURL: 'https://carstats-8585a-default-rtdb.firebaseio.com',
    storageBucket: 'carstats-8585a.appspot.com',
    iosBundleId: 'com.example.sdfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC12zLSq8YyJ2ivXLAU9neB7-7IUDJNByE',
    appId: '1:994981518011:ios:1b7581335872623fd1279e',
    messagingSenderId: '994981518011',
    projectId: 'carstats-8585a',
    databaseURL: 'https://carstats-8585a-default-rtdb.firebaseio.com',
    storageBucket: 'carstats-8585a.appspot.com',
    iosBundleId: 'com.example.sdfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiHephvCyyD5Gy1Ga0hbfQUZSIDYgCziA',
    appId: '1:994981518011:web:c30306babbf6756ad1279e',
    messagingSenderId: '994981518011',
    projectId: 'carstats-8585a',
    authDomain: 'carstats-8585a.firebaseapp.com',
    databaseURL: 'https://carstats-8585a-default-rtdb.firebaseio.com',
    storageBucket: 'carstats-8585a.appspot.com',
    measurementId: 'G-RWF2FY09PX',
  );
}
